spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 409663827068-30dqtof3b70gumj9t53in13mc96krmbs.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile


